import { randomUUID } from 'node:crypto';
import { chmod, mkdir, open, readFile, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import { withFileLock } from '@avdm/core';
import type { AccountDetails, AccountPatch, GameAccount, ScriptParams, ScriptParamValue } from './types';

/** Version 2 added `defaultScriptId` / `scriptParams`; version 1 files are read and upgraded on the next write. */
const FILE_VERSION = 2;
const MAX_FILE_BYTES = 4 * 1024 * 1024;
const MAX_ACCOUNTS = 512;
const MAX_SCRIPT_SCOPES = 64;
const MAX_PARAMS_PER_SCRIPT = 64;
const MAX_PARAM_STRING = 64 * 1024;
const MAX_ACCOUNT_PARAMS_BYTES = 128 * 1024;
const GAME_ID_RE = /^[a-z][a-z0-9-]{0,63}$/;
const PACKAGE_RE = /^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)+$/;
/** Stored ids (and login attempt ids) keep the shape version 1 accepted. */
const STORED_ID_RE = /^[0-9a-f-]{36}$/i;
/** Ids generated by the renderer for inline creation must be real UUIDs. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
/** Same id rule as scripts, plans and plan task parameters. */
const SCRIPT_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,95}$/;
/** Old wanlong-panel account ids (`acc_…`), kept only to recognise a second import of the same file. */
const LEGACY_ID_RE = /^[^\0-\x1f\x7f]{1,120}$/;

interface AccountFile { version: 2; accounts: GameAccount[] }

/** An account error the renderer can branch on (`errorCodeOf`), e.g. to offer a confirmed takeover. */
export class AccountError extends Error {
  constructor(readonly code: 'ACCOUNT_SLOT_TAKEN' | 'ACCOUNT_BOUND_ELSEWHERE' | 'ACCOUNT_ID_TAKEN', message: string) {
    super(message);
    this.name = 'AccountError';
  }
}

/** The refusal of binding an instance another account owns; the renderer offers a confirmed takeover. */
export function slotTakenError(index: number, ownerName: string): AccountError {
  return new AccountError('ACCOUNT_SLOT_TAKEN', `实例 #${index} 已绑定「${ownerName}」。改绑后「${ownerName}」将解除绑定并需要重新登录。`);
}

export interface BindOutcome {
  account: GameAccount;
  displaced: GameAccount | null;
}

export interface LegacyAccountRow {
  oldId: string;
  details: AccountDetails;
  defaultScriptId?: string;
  scriptParams?: ScriptParams;
}

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function validTime(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0;
}

export function isAccountId(value: unknown): value is string {
  return typeof value === 'string' && STORED_ID_RE.test(value);
}

/** A client-generated id for an account that may not exist yet (the wizard's 「新建账号」). */
export function isNewAccountId(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}

function text(value: unknown, label: string, max: number, required: boolean): string {
  if (typeof value !== 'string') throw new Error(`${label}必须是文字`);
  const clean = value.trim();
  if ((required && !clean) || clean.length > max || /[\0\r\n]/.test(clean)) {
    throw new Error(`${label}长度或内容无效`);
  }
  return clean;
}

/** Validated, trimmed account details (throws the Chinese reason). */
export function accountDetails(value: AccountDetails): Required<AccountDetails> {
  return details(value);
}

function details(value: AccountDetails): Required<AccountDetails> {
  if (!record(value)) throw new Error('账号资料无效');
  return {
    name: text(value.name, '账号名称', 100, true),
    server: text(value.server ?? '', '服务器', 100, false),
    role: text(value.role ?? '', '角色名称', 100, false),
    note: text(value.note ?? '', '备注', 1000, false),
  };
}

function scriptId(value: unknown, label = '默认脚本'): string {
  if (typeof value !== 'string' || !SCRIPT_ID_RE.test(value)) throw new Error(`${label}编号无效`);
  return value;
}

function paramValue(value: unknown): ScriptParamValue {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.length <= MAX_PARAM_STRING && !value.includes('\0')) return value;
  throw new Error('脚本参数值只能是有限数字、布尔值或 64 KB 以内的文字');
}

/** One script's parameter overrides: bounded key count, id-shaped keys, scalar values. */
export function normalizeScriptParamSet(value: unknown): Record<string, ScriptParamValue> {
  if (!record(value)) throw new Error('脚本参数无效');
  const entries = Object.entries(value);
  if (entries.length > MAX_PARAMS_PER_SCRIPT) throw new Error(`每个脚本最多保存 ${MAX_PARAMS_PER_SCRIPT} 个参数`);
  const out: Record<string, ScriptParamValue> = {};
  for (const [key, raw] of entries) {
    if (!SCRIPT_ID_RE.test(key)) throw new Error(`脚本参数名无效：${key.slice(0, 40)}`);
    out[key] = paramValue(raw);
  }
  return out;
}

function normalizeScriptParams(value: unknown): ScriptParams | undefined {
  if (value === undefined) return undefined;
  if (!record(value)) throw new Error('脚本参数无效');
  const entries = Object.entries(value);
  if (entries.length > MAX_SCRIPT_SCOPES) throw new Error(`每个账号最多保存 ${MAX_SCRIPT_SCOPES} 个脚本的参数`);
  const out: ScriptParams = {};
  for (const [id, params] of entries) {
    const set = normalizeScriptParamSet(params);
    if (Object.keys(set).length > 0) out[scriptId(id, '脚本')] = set;
  }
  if (Buffer.byteLength(JSON.stringify(out)) > MAX_ACCOUNT_PARAMS_BYTES) throw new Error('账号的脚本参数超过 128 KB 上限');
  return Object.keys(out).length ? out : undefined;
}

function parseAccount(value: unknown): GameAccount {
  if (!record(value)) throw new Error('账号记录无效');
  const id = value.id;
  const gameId = value.gameId;
  const packageName = value.packageName;
  if (!isAccountId(id) || typeof gameId !== 'string' || !GAME_ID_RE.test(gameId) ||
    typeof packageName !== 'string' || !PACKAGE_RE.test(packageName)) throw new Error('账号标识无效');
  const binding = value.binding;
  if (binding !== null && (!record(binding) || !Number.isInteger(binding.index) ||
    (binding.index as number) < 0 || (binding.index as number) > 63 ||
    typeof binding.instanceCreatedAt !== 'string' || !binding.instanceCreatedAt)) {
    throw new Error('账号实例绑定无效');
  }
  const login = value.login;
  if (!record(login) || (login.status !== 'pending' && login.status !== 'ready') ||
    (login.attemptId !== null && !isAccountId(login.attemptId)) ||
    (login.verifiedAt !== null && !validTime(login.verifiedAt)) ||
    (login.status === 'ready' && (binding === null || login.verifiedAt === null))) {
    throw new Error('账号登录状态无效');
  }
  if (typeof value.enabled !== 'boolean' || (value.enabled && login.status !== 'ready') ||
    !validTime(value.createdAt) || !validTime(value.updatedAt)) throw new Error('账号状态无效');
  const names = details({ name: value.name as string, server: value.server as string,
    role: value.role as string, note: value.note as string });
  const account: GameAccount = {
    id, gameId, packageName, ...names, enabled: value.enabled,
    binding: binding === null ? null : { index: binding.index as number, instanceCreatedAt: binding.instanceCreatedAt as string },
    login: { status: login.status as 'pending' | 'ready', attemptId: login.attemptId as string | null,
      verifiedAt: login.verifiedAt as number | null },
    createdAt: value.createdAt, updatedAt: value.updatedAt,
  };
  if (value.defaultScriptId !== undefined && value.defaultScriptId !== null) account.defaultScriptId = scriptId(value.defaultScriptId);
  const params = normalizeScriptParams(value.scriptParams);
  if (params) account.scriptParams = params;
  if (value.legacyId !== undefined) {
    if (typeof value.legacyId !== 'string' || !LEGACY_ID_RE.test(value.legacyId)) throw new Error('账号导入来源无效');
    account.legacyId = value.legacyId;
  }
  return account;
}

function parseFile(raw: unknown): AccountFile {
  // Version 1 predates defaultScriptId / scriptParams; its records are otherwise identical.
  if (!record(raw) || (raw.version !== 1 && raw.version !== FILE_VERSION) || !Array.isArray(raw.accounts) ||
    raw.accounts.length > MAX_ACCOUNTS) {
    throw new Error('账号文件格式不兼容');
  }
  const accounts = raw.accounts.map(parseAccount);
  const ids = new Set<string>();
  const bindings = new Set<string>();
  for (const account of accounts) {
    if (ids.has(account.id)) throw new Error('账号文件存在重复编号');
    ids.add(account.id);
    if (account.binding) {
      const key = `${account.gameId}:${account.binding.index}`;
      if (bindings.has(key)) throw new Error('账号文件存在重复实例绑定');
      bindings.add(key);
    }
  }
  return { version: FILE_VERSION, accounts };
}

function sameBinding(a: GameAccount['binding'], b: GameAccount['binding']): boolean {
  return a?.index === b?.index && a?.instanceCreatedAt === b?.instanceCreatedAt;
}

function resetLogin(account: GameAccount): void {
  account.login = { status: 'pending', attemptId: null, verifiedAt: null };
  account.enabled = false;
}

/** Cross-process serialized, private, atomic account metadata. Never stores phone or SMS codes. */
export class AccountStore {
  readonly file: string;

  constructor(home: string) {
    if (!path.isAbsolute(home)) throw new Error('账号数据目录必须是绝对路径');
    this.file = path.join(home, 'automation', 'accounts.json');
  }

  private async read(): Promise<AccountFile> {
    let json: string;
    try {
      const metadata = await stat(this.file);
      if (metadata.size > MAX_FILE_BYTES) throw new Error('账号文件超过 4 MB');
      json = await readFile(this.file, 'utf8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return { version: FILE_VERSION, accounts: [] };
      throw error;
    }
    try { return parseFile(JSON.parse(json) as unknown); }
    catch (error) { throw new Error(`账号文件无法读取：${(error as Error).message}（${this.file}）`); }
  }

  private async write(data: AccountFile): Promise<void> {
    const valid = parseFile(data);
    const json = JSON.stringify(valid, null, 2) + '\n';
    if (Buffer.byteLength(json) > MAX_FILE_BYTES) throw new Error('账号文件超过 4 MB');
    await mkdir(path.dirname(this.file), { recursive: true, mode: 0o700 });
    const temp = `${this.file}.${randomUUID()}.tmp`;
    try {
      const handle = await open(temp, 'wx', 0o600);
      try { await handle.writeFile(json); await handle.sync(); }
      finally { await handle.close(); }
      await rename(temp, this.file);
      await chmod(this.file, 0o600);
    } catch (error) {
      await rm(temp, { force: true }).catch(() => undefined);
      throw error;
    }
  }

  private async change<T>(fn: (data: AccountFile) => Promise<T> | T): Promise<T> {
    return withFileLock(`${this.file}.lock`, async () => {
      const data = await this.read();
      const result = await fn(data);
      await this.write(data);
      return result;
    });
  }

  async list(gameId?: string): Promise<GameAccount[]> {
    if (gameId !== undefined && !GAME_ID_RE.test(gameId)) throw new Error('游戏编号无效');
    const accounts = (await this.read()).accounts;
    return accounts.filter((item) => !gameId || item.gameId === gameId)
      .sort((a, b) => a.createdAt - b.createdAt).map((item) => structuredClone(item));
  }

  async get(id: string): Promise<GameAccount | null> {
    const found = (await this.read()).accounts.find((item) => item.id === id);
    return found ? structuredClone(found) : null;
  }

  /**
   * Create an account. A client-generated `id` makes creation idempotent: the same id for the same game returns
   * the existing record (a retried 「新建账号」 never creates a duplicate).
   */
  async create(gameId: string, packageName: string, input: AccountDetails,
    opts: { id?: string; defaultScriptId?: string | null } = {}): Promise<GameAccount> {
    if (!GAME_ID_RE.test(gameId) || !PACKAGE_RE.test(packageName)) throw new Error('游戏标识无效');
    if (opts.id !== undefined && !isNewAccountId(opts.id)) throw new Error('账号编号无效');
    const names = details(input);
    const defaultScriptId = opts.defaultScriptId ? scriptId(opts.defaultScriptId) : undefined;
    return this.change((data) => {
      if (opts.id) {
        const existing = data.accounts.find((item) => item.id === opts.id);
        if (existing) {
          if (existing.gameId !== gameId) throw new AccountError('ACCOUNT_ID_TAKEN', '账号编号已被其他游戏的账号占用');
          return structuredClone(existing);
        }
      }
      if (data.accounts.length >= MAX_ACCOUNTS) throw new Error('账号数量已达上限');
      const now = Date.now();
      const account: GameAccount = {
        id: opts.id ?? randomUUID(), gameId, packageName, ...names, enabled: false, binding: null,
        login: { status: 'pending', attemptId: null, verifiedAt: null }, createdAt: now, updatedAt: now,
      };
      if (defaultScriptId) account.defaultScriptId = defaultScriptId;
      data.accounts.push(account);
      return structuredClone(account);
    });
  }

  /** Details and the default script only: login state, binding and the enable switch cannot be forged here. */
  async update(id: string, patch: AccountPatch): Promise<GameAccount> {
    if (!record(patch as unknown)) throw new Error('账号资料无效');
    const defaultScriptId = patch.defaultScriptId === undefined ? undefined
      : patch.defaultScriptId === null || patch.defaultScriptId === '' ? null : scriptId(patch.defaultScriptId);
    return this.change((data) => {
      const account = data.accounts.find((item) => item.id === id);
      if (!account) throw new Error('账号不存在');
      const next = details({ name: patch.name ?? account.name, server: patch.server ?? account.server,
        role: patch.role ?? account.role, note: patch.note ?? account.note });
      Object.assign(account, next, { updatedAt: Date.now() });
      if (defaultScriptId === null) delete account.defaultScriptId;
      else if (defaultScriptId !== undefined) account.defaultScriptId = defaultScriptId;
      return structuredClone(account);
    });
  }

  /** Replace (or with `null` remove) one script's parameter overrides. */
  async setScriptParams(id: string, script: string, params: Record<string, ScriptParamValue> | null): Promise<GameAccount> {
    const key = scriptId(script, '脚本');
    const set = params === null ? null : normalizeScriptParamSet(params);
    return this.change((data) => {
      const account = data.accounts.find((item) => item.id === id);
      if (!account) throw new Error('账号不存在');
      const next: ScriptParams = { ...(account.scriptParams ?? {}) };
      if (set && Object.keys(set).length > 0) next[key] = set;
      else delete next[key];
      const normalized = normalizeScriptParams(next);
      if (normalized) account.scriptParams = normalized;
      else delete account.scriptParams;
      account.updatedAt = Date.now();
      return structuredClone(account);
    });
  }

  async remove(id: string): Promise<void> {
    await this.change((data) => {
      const i = data.accounts.findIndex((item) => item.id === id);
      if (i < 0) throw new Error('账号不存在');
      data.accounts.splice(i, 1);
    });
  }

  /**
   * Bind or unbind. One account per (game, instance): an instance owned by another account is refused unless the
   * caller passes `takeOver` after the user confirmed it; the displaced account is then unbound, reset to
   * pending and disabled in the same transaction. Rebinding to a different instance (or a replaced AVD) resets
   * this account's login; re-binding the identical binding keeps it verified.
   *
   * With `create`, a missing account is created under `id` (a client UUID) and bound in the same transaction
   * (original account:save with an instance): a refused bind leaves no orphan account behind.
   */
  async bind(id: string, binding: GameAccount['binding'], opts: {
    takeOver?: boolean;
    create?: { gameId: string; packageName: string; details: AccountDetails };
  } = {}): Promise<BindOutcome> {
    const create = opts.create;
    const names = create ? details(create.details) : null;
    if (create && (!isNewAccountId(id) || !GAME_ID_RE.test(create.gameId) || !PACKAGE_RE.test(create.packageName))) {
      throw new Error('账号编号或游戏标识无效');
    }
    return this.change((data) => {
      let account = data.accounts.find((item) => item.id === id);
      if (account && create && account.gameId !== create.gameId) {
        throw new AccountError('ACCOUNT_ID_TAKEN', '账号编号已被其他游戏的账号占用');
      }
      if (!account && (!create || !names || !binding)) throw new Error('账号不存在');
      if (binding && (!Number.isInteger(binding.index) || binding.index < 0 || binding.index > 63 || !binding.instanceCreatedAt)) {
        throw new Error('实例绑定无效');
      }
      const gameId = account?.gameId ?? create!.gameId;
      const owner = binding ? data.accounts.find((item) => item.id !== id && item.gameId === gameId &&
        item.binding?.index === binding.index) : undefined;
      let displaced: GameAccount | null = null;
      if (owner) {
        if (!opts.takeOver) throw slotTakenError(binding!.index, owner.name);
        owner.binding = null;
        resetLogin(owner);
        owner.updatedAt = Date.now();
        displaced = structuredClone(owner);
      }
      if (!account) {
        if (data.accounts.length >= MAX_ACCOUNTS) throw new Error('账号数量已达上限');
        const now = Date.now();
        account = {
          id, gameId: create!.gameId, packageName: create!.packageName, ...names!, enabled: false, binding: null,
          login: { status: 'pending', attemptId: null, verifiedAt: null }, createdAt: now, updatedAt: now,
        };
        data.accounts.push(account);
      }
      if (!sameBinding(account.binding, binding)) resetLogin(account);
      account.binding = binding;
      account.updatedAt = Date.now();
      return { account: structuredClone(account), displaced };
    });
  }

  async setEnabled(id: string, enabled: boolean): Promise<GameAccount> {
    if (typeof enabled !== 'boolean') throw new Error('启用状态无效');
    return this.change((data) => {
      const account = data.accounts.find((item) => item.id === id);
      if (!account) throw new Error('账号不存在');
      if (enabled && (account.login.status !== 'ready' || !account.binding)) throw new Error('请先完成登录向导，再启用该账号');
      account.enabled = enabled;
      account.updatedAt = Date.now();
      return structuredClone(account);
    });
  }

  /**
   * Bind without stealing another account, then mark this login attempt pending. With `create`, a missing
   * account is created inline under the same id (the wizard's 「新建账号」), so retries never duplicate it.
   */
  async prepareLogin(
    id: string, binding: NonNullable<GameAccount['binding']>, attemptId: string,
    create?: { gameId: string; packageName: string; details: AccountDetails },
  ): Promise<GameAccount> {
    if (!isAccountId(id)) throw new Error('账号编号无效');
    const names = create ? details(create.details) : null;
    return this.change((data) => {
      let account = data.accounts.find((item) => item.id === id);
      const gameId = account?.gameId ?? create?.gameId;
      const owner = data.accounts.find((item) => item.id !== id && item.gameId === gameId && item.binding?.index === binding.index);
      if (owner) {
        throw new AccountError('ACCOUNT_SLOT_TAKEN', `实例已绑定「${owner.name}」，请使用该账号继续登录，或先解除原绑定。`);
      }
      if (account?.binding && !sameBinding(account.binding, binding)) {
        throw new AccountError('ACCOUNT_BOUND_ELSEWHERE', '该账号已绑定其他实例，或原实例已被替换，请先解除绑定。');
      }
      if (!account) {
        if (!create || !names) throw new Error('账号不存在');
        if (!isNewAccountId(id)) throw new Error('账号编号无效');
        if (!GAME_ID_RE.test(create.gameId) || !PACKAGE_RE.test(create.packageName)) throw new Error('游戏标识无效');
        if (data.accounts.length >= MAX_ACCOUNTS) throw new Error('账号数量已达上限');
        const now = Date.now();
        account = {
          id, gameId: create.gameId, packageName: create.packageName, ...names, enabled: false, binding: null,
          login: { status: 'pending', attemptId: null, verifiedAt: null }, createdAt: now, updatedAt: now,
        };
        data.accounts.push(account);
      } else if (create && (account.gameId !== create.gameId || account.packageName !== create.packageName)) {
        throw new Error('账号和游戏不匹配');
      }
      account.binding = binding;
      account.login = { status: 'pending', attemptId, verifiedAt: null };
      account.enabled = false;
      account.updatedAt = Date.now();
      return structuredClone(account);
    });
  }

  /** A stale session or recycled AVD index cannot enable a different account/device. */
  async completeLogin(id: string, binding: NonNullable<GameAccount['binding']>, attemptId: string): Promise<GameAccount> {
    return this.change((data) => {
      const account = data.accounts.find((item) => item.id === id);
      if (!account || account.binding?.index !== binding.index ||
        account.binding.instanceCreatedAt !== binding.instanceCreatedAt ||
        account.login.status !== 'pending' || account.login.attemptId !== attemptId) {
        throw new Error('账号绑定或登录会话已变化，请重新开始登录');
      }
      const now = Date.now();
      account.login = { status: 'ready', attemptId: null, verifiedAt: now };
      account.enabled = true;
      account.updatedAt = now;
      return structuredClone(account);
    });
  }

  /**
   * Create legacy accounts in one transaction: unbound, pending and disabled, each remembering its old id. Rows
   * imported before (same game, same old id) are not touched and map to that account. Returns old id → new id.
   */
  async importLegacy(gameId: string, packageName: string, rows: LegacyAccountRow[]):
    Promise<{ idMap: Record<string, string>; created: number }> {
    if (!GAME_ID_RE.test(gameId) || !PACKAGE_RE.test(packageName)) throw new Error('游戏标识无效');
    const prepared = rows.map((row) => {
      if (typeof row.oldId !== 'string' || !LEGACY_ID_RE.test(row.oldId)) throw new Error('旧账号编号无效');
      return {
        oldId: row.oldId, names: details(row.details),
        defaultScriptId: row.defaultScriptId === undefined ? undefined : scriptId(row.defaultScriptId),
        scriptParams: normalizeScriptParams(row.scriptParams),
      };
    });
    return this.change((data) => {
      const map: Record<string, string> = {};
      const fresh = prepared.filter((row) => {
        const previous = data.accounts.find((item) => item.gameId === gameId && item.legacyId === row.oldId);
        if (previous) map[row.oldId] = previous.id;
        return !previous;
      });
      if (data.accounts.length + fresh.length > MAX_ACCOUNTS) throw new Error('账号数量将超过上限，未导入');
      const now = Date.now();
      for (const row of fresh) {
        const account: GameAccount = {
          id: randomUUID(), gameId, packageName, ...row.names, enabled: false, binding: null,
          login: { status: 'pending', attemptId: null, verifiedAt: null }, legacyId: row.oldId, createdAt: now, updatedAt: now,
        };
        if (row.defaultScriptId) account.defaultScriptId = row.defaultScriptId;
        if (row.scriptParams) account.scriptParams = row.scriptParams;
        data.accounts.push(account);
        map[row.oldId] = account.id;
      }
      return { idMap: map, created: fresh.length };
    });
  }
}
